### ISSUE TITLE
Idea: Advanced matching ala SugarJS

### ISSUE THREAD

**Issue by timoxley** [component/enumerable#8]
[Sugar.js](http://sugarjs.com/) has this '[advanced matching](http://sugarjs.com/arrays#matching)' for  its enumerable methods. You've already started down this path with the `String|Function` signatures for methods like `find` and `reject`, but this takes it a step further, introducing `Regex` and `Object` matching (among others).

I've adapted the example from the Sugar site for `component/enumerable` so you can get an idea of how it could work:

``` js
var people = Enumerable([
  { name: 'john', age: 21 },
  { name: 'jane', age: 54 },
  { name: 'bill', age: 16 },
  { name: 'john', age: 88 },
  { name: 'will', age: 8 }
]);

people.select({ name: 'john', age: 21 })
> [{"name":"john","age":21}]

people.select({ age: 21 })
> [{"name":"john","age":21}]

people.select({ name: 'john' })
> [{"name":"john","age":21},{"name":"john","age":88}]

people.select({ name: /ill$/ })
> [{"name":"bill","age":16},{"name":"will","age":8}]

people.select({
  age: function(age) {
    return age < 20;
  }
}) 
> [{"name":"bill","age":16},{"name":"will","age":8}]


Enumerable([1, 2, 3]).find(3)
> 3
Enumerable([55, 100, 55, 72]).count(55)
> 2
Enumerable([55, 100, 55, 72]).count(function(n) {
  return n > 80;
}) 
> 1

Enumerable(['a', 'b', 'c']).reject('b') 
> ["a","c"]

Enumerable(['a', 'b', 'c']).none('d') 
> true

Enumerable(['big', 'pig', 'bag']).count(/g$/)
> 3
Enumerable(['big', 'pig', 'bag']).count(/ig$/)
> 2

Enumerable([ [1,2], [2,3] ]).any([2,3])
> true

Enumerable([ [1,2], [2,3] ]).all([2,3])
> false
```

Had a quick look through the sugar code and doesn't look like this can be easily lifted straight from sugar, but also doesn't look like it would be too hard to implement as a separate 'matcher' component.

**Comment by tj** [comment]
im down, it would be pretty trivial to implement. I think we should add it to-function since that's kinda the universal function generator thing I've been going with, everything else benefits. I dont have it compiling functions with `Function`  yet but we could possibly go down that path or just keep it as a closure like I have now, doesn't really matter to me, if people need better perf they should just do straight loops anyway so I'm +1

**Comment by timoxley** [comment]
Sounds good.

> … everything else benefits 

this is the best part.
